Add missing semicolon
The missing semicolon caused compilation to fail:

BMP280_DEV.h:200:3: error: expected ';' before 'int32_t'

   int32_t t_fine;                       // Bosch t_fine variable